### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by thangngoc89** [sanderdatema/import_facebook_into_discourse#1]
I use your importer on the lastest Discourse 1.20beta3
and this is log when I run the importer (with test mode, everything are fine)

*\* Invoke import:facebook_group (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute import:facebook_group

**\* Using fake email addresses

Facebook token accepted
Batch: 98 posts (since 04/09/2014 15:15 until 28/11/2014 10:43)

Amount of posts: 98
Amount of writers: 15
rake aborted!
NoMethodError: undefined method `tr' for nil:NilClass
/var/www/discourse/lib/tasks/import_facebook.rake:359:in`fb_username_to_dc'
/var/www/discourse/lib/tasks/import_facebook.rake:247:in `block in dc_create_users_from_fb_writers'
/var/www/discourse/lib/tasks/import_facebook.rake:245:in`each'
/var/www/discourse/lib/tasks/import_facebook.rake:245:in `dc_create_users_from_fb_writers'
/var/www/discourse/lib/tasks/import_facebook.rake:67:in`block in <top (required)>'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:240:in`block in execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:235:in`execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/task.rb:165:in`invoke'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:156:in `invoke_task'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:112:in`block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:112:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:112:in`block in top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:121:in `run_with_threads'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:106:in`top_level'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:84:in `block in run'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:182:in`standard_exception_handling'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/application.rb:79:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/rake-10.4.0/bin/rake:33:in`<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in`<main>'
Tasks: TOP => import:facebook_group

Can you help me to make this work?

**Comment by And2Devel** [comment]
look here: https://github.com/VannillaSky/import_facebook_into_discourse

**Comment by sanderdatema** [comment]
Now that @VannillaSky updated this script, it should work again.
